source 'https://github.com/CocoaPods/Specs.git'

target 'PiingApp' do

pod 'MFSideMenu’
pod 'RESideMenu'
pod 'CardIO', '~> 5.0'
pod 'Fabric'
pod 'Crashlytics'
pod 'GoogleMaps’, ‘~> 1.10.1’
pod 'Reachability'
pod 'AFNetworking', '~> 3.0'
pod 'iOS-Color-Picker'

end
